[book]
title = "Digital Tails"
author = "Kesten Broughton"
description = "Security focused enhancements to MediaSmarts digital and media literacy materials"
language = "en"
multilingual = false
src = "src"
